<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit272d6887e3cebaf19e8762c9b6aaf73b
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rolands\\Portfolio\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rolands\\Portfolio\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit272d6887e3cebaf19e8762c9b6aaf73b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit272d6887e3cebaf19e8762c9b6aaf73b::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit272d6887e3cebaf19e8762c9b6aaf73b::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit272d6887e3cebaf19e8762c9b6aaf73b::$classMap;

        }, null, ClassLoader::class);
    }
}
