<?php require 'C:/laragon/www/Portfolio/layouts/header.phtml'; ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Protfolio</title>
</head>
<body>
    <a href = '/index.php?controller=index&action=index'>
    <Button>Home</Button>
    </a>
    <a href= '/index.php?controller=Register&action=Register'>
    <Button>Register</Button>
    </a>
</body>


<?php require 'C:/laragon/www/Portfolio/layouts/footer.phtml'; ?>