<?php require 'C:/laragon/www/Portfolio/layouts/header.phtml'; ?>

<form method="post" action="/index.php?controller=Register&action=<?php echo $action; ?>">
    <input type="text" name="FirstName"><br>
    <input type="text" name="LastName"><br>
    <input type="email" name="Email"><br>
    <input type="submit" value="ok">
</form>


<?php require 'C:/laragon/www/Portfolio/layouts/footer.phtml'; ?>